# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1228ddc8a8f6894807243446463cc4f6717d208dd30967735bba3551d1c87fd40b0d0b50e835b5b0cccf5f056528c8953a23cd959eaa64fd1cdf22c7245c9ad4

test:
  secret_key_base: c46269ea0c738b27e798529450d8fd52d91f5ff116bb6aecc4037972e675b666078bd665bd1eacde517db374f4061769b106beae64cb42109c63447d383bc05e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
